// pages/_app.js or similar root layout file
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { CartProvider } from "@/contexts/CartContext";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { unstable_setRequestLocale } from "next-intl/server";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { locales } from "@/navigation";

const roboto = Montserrat({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export function generateStaticParams() {
  return locales.map((lang) => ({ lang }));
}

export const metadata = {
  title: "Oltiariq innovatsion markazi",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  const { lang } = params;
  unstable_setRequestLocale(lang);
  const messages = useMessages();

  return (
    <html lang={lang}>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={roboto.className}>
        <NextIntlClientProvider locale={lang} messages={messages}>
          <CartProvider>
            <Header />
            <main>{children}</main>
            <Footer />
          </CartProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
